apiVersion: v1
kind: ConfigMap
metadata:
  name: kubemarket-config
  namespace: kubemarket
data:
  NODE_ENV: "production"
  PORT: "4000"
  JWT_EXPIRES_IN: "1d"
  FRONTEND_ORIGIN: "http://kubemarket.local"
  POSTGRES_DB: "kubemarket"
  POSTGRES_USER: "kubemarket"
