apiVersion: v1
kind: Secret
metadata:
  name: kubemarket-secret
  namespace: kubemarket
type: Opaque
stringData:
  POSTGRES_PASSWORD: "replace-me-kubemarket-password"
  JWT_SECRET: "replace-me-with-a-long-random-secret"
  DATABASE_URL: "postgres://kubemarket:replace-me-kubemarket-password@postgres:5432/kubemarket"
