apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kubemarket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: malubullul/kubemarket-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: kubemarket-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: kubemarket-config
                  key: PORT
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: kubemarket-config
                  key: JWT_EXPIRES_IN
            - name: FRONTEND_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: kubemarket-config
                  key: FRONTEND_ORIGIN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubemarket-secret
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kubemarket-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kubemarket
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
